// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mod struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	NexusID     pgtype.Int4      `json:"nexus_id"`
	Author      pgtype.Text      `json:"author"`
	Description pgtype.Text      `json:"description"`
	SourceUrl   pgtype.Text      `json:"source_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ModFile struct {
	ID                int32            `json:"id"`
	ModID             int32            `json:"mod_id"`
	Filename          string           `json:"filename"`
	FilePath          string           `json:"file_path"`
	CurrentVersion    string           `json:"current_version"`
	LatestVersion     pgtype.Text      `json:"latest_version"`
	GameVersionCompat string           `json:"game_version_compat"`
	IsEnabled         bool             `json:"is_enabled"`
	Hash              pgtype.Text      `json:"hash"`
	InstalledAt       pgtype.Timestamp `json:"installed_at"`
}

type Modlist struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedBy   pgtype.Text      `json:"created_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ModlistJunction struct {
	ModlistID pgtype.UUID `json:"modlist_id"`
	ModID     int32       `json:"mod_id"`
}
