// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureDefaultModProfile = `-- name: EnsureDefaultModProfile :exec
INSERT INTO mods (id, name, author, description, source_url)
VALUES (
        1,
        'Unassigned Local Mods',
        'System',
        'Placeholder profile for scanned local game files.',
        ''
    ) ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureDefaultModProfile(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureDefaultModProfile)
	return err
}

const getModByFilename = `-- name: GetModByFilename :one
SELECT m.id, m.name, m.nexus_id, m.author, m.description, m.source_url, m.created_at, m.updated_at,
    mf.filename,
    mf.current_version,
    mf.latest_version,
    mf.is_enabled
FROM mods m
    JOIN mod_files mf ON m.id = mf.mod_id
WHERE mf.filename = $1
`

type GetModByFilenameRow struct {
	ID             int32            `json:"id"`
	Name           string           `json:"name"`
	NexusID        pgtype.Int4      `json:"nexus_id"`
	Author         pgtype.Text      `json:"author"`
	Description    pgtype.Text      `json:"description"`
	SourceUrl      pgtype.Text      `json:"source_url"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Filename       string           `json:"filename"`
	CurrentVersion string           `json:"current_version"`
	LatestVersion  pgtype.Text      `json:"latest_version"`
	IsEnabled      bool             `json:"is_enabled"`
}

func (q *Queries) GetModByFilename(ctx context.Context, filename string) (GetModByFilenameRow, error) {
	row := q.db.QueryRow(ctx, getModByFilename, filename)
	var i GetModByFilenameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NexusID,
		&i.Author,
		&i.Description,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Filename,
		&i.CurrentVersion,
		&i.LatestVersion,
		&i.IsEnabled,
	)
	return i, err
}

const getModlistFilesByListID = `-- name: GetModlistFilesByListID :many
SELECT mf.id,
    mf.filename,
    mf.file_path,
    mf.is_enabled
FROM modlist_junction mlm -- Fixed table name here
    JOIN mod_files mf ON mlm.mod_id = mf.mod_id
WHERE mlm.modlist_id = $1
`

type GetModlistFilesByListIDRow struct {
	ID        int32  `json:"id"`
	Filename  string `json:"filename"`
	FilePath  string `json:"file_path"`
	IsEnabled bool   `json:"is_enabled"`
}

func (q *Queries) GetModlistFilesByListID(ctx context.Context, modlistID pgtype.UUID) ([]GetModlistFilesByListIDRow, error) {
	rows, err := q.db.Query(ctx, getModlistFilesByListID, modlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModlistFilesByListIDRow
	for rows.Next() {
		var i GetModlistFilesByListIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.FilePath,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModlistWithMods = `-- name: GetModlistWithMods :many
SELECT ml.name AS modlist_name,
    m.name AS mod_name,
    mf.filename,
    mf.hash
FROM modlists ml
    JOIN modlist_junction mlm ON ml.id = mlm.modlist_id -- Fixed table name here
    JOIN mods m ON mlm.mod_id = m.id
    JOIN mod_files mf ON m.id = mf.mod_id
WHERE ml.id = $1
`

type GetModlistWithModsRow struct {
	ModlistName string      `json:"modlist_name"`
	ModName     string      `json:"mod_name"`
	Filename    string      `json:"filename"`
	Hash        pgtype.Text `json:"hash"`
}

func (q *Queries) GetModlistWithMods(ctx context.Context, id pgtype.UUID) ([]GetModlistWithModsRow, error) {
	rows, err := q.db.Query(ctx, getModlistWithMods, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModlistWithModsRow
	for rows.Next() {
		var i GetModlistWithModsRow
		if err := rows.Scan(
			&i.ModlistName,
			&i.ModName,
			&i.Filename,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModsIncompatibleWithGameVersion = `-- name: GetModsIncompatibleWithGameVersion :many
SELECT id,
    filename,
    file_path
FROM mod_files
WHERE game_version_compat <> $1
    AND is_enabled = TRUE
`

type GetModsIncompatibleWithGameVersionRow struct {
	ID       int32  `json:"id"`
	Filename string `json:"filename"`
	FilePath string `json:"file_path"`
}

func (q *Queries) GetModsIncompatibleWithGameVersion(ctx context.Context, gameVersionCompat string) ([]GetModsIncompatibleWithGameVersionRow, error) {
	rows, err := q.db.Query(ctx, getModsIncompatibleWithGameVersion, gameVersionCompat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModsIncompatibleWithGameVersionRow
	for rows.Next() {
		var i GetModsIncompatibleWithGameVersionRow
		if err := rows.Scan(&i.ID, &i.Filename, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutdatedModFiles = `-- name: GetOutdatedModFiles :many
SELECT id,
    filename,
    file_path
FROM mod_files
WHERE current_version <> latest_version
`

type GetOutdatedModFilesRow struct {
	ID       int32  `json:"id"`
	Filename string `json:"filename"`
	FilePath string `json:"file_path"`
}

func (q *Queries) GetOutdatedModFiles(ctx context.Context) ([]GetOutdatedModFilesRow, error) {
	rows, err := q.db.Query(ctx, getOutdatedModFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutdatedModFilesRow
	for rows.Next() {
		var i GetOutdatedModFilesRow
		if err := rows.Scan(&i.ID, &i.Filename, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMod = `-- name: InsertMod :one
INSERT INTO mods (name, nexus_id, author, description, source_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, nexus_id, author, description, source_url, created_at, updated_at
`

type InsertModParams struct {
	Name        string      `json:"name"`
	NexusID     pgtype.Int4 `json:"nexus_id"`
	Author      pgtype.Text `json:"author"`
	Description pgtype.Text `json:"description"`
	SourceUrl   pgtype.Text `json:"source_url"`
}

func (q *Queries) InsertMod(ctx context.Context, arg InsertModParams) (Mod, error) {
	row := q.db.QueryRow(ctx, insertMod,
		arg.Name,
		arg.NexusID,
		arg.Author,
		arg.Description,
		arg.SourceUrl,
	)
	var i Mod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NexusID,
		&i.Author,
		&i.Description,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveScannedModFile = `-- name: SaveScannedModFile :one
INSERT INTO mod_files (
        mod_id,
        filename,
        file_path,
        current_version,
        latest_version
    )
VALUES ($1, $2, $3, $4, $5) ON CONFLICT (filename) DO
UPDATE
SET file_path = excluded.file_path
RETURNING id, mod_id, filename, file_path, current_version, latest_version, game_version_compat, is_enabled, hash, installed_at
`

type SaveScannedModFileParams struct {
	ModID          int32       `json:"mod_id"`
	Filename       string      `json:"filename"`
	FilePath       string      `json:"file_path"`
	CurrentVersion string      `json:"current_version"`
	LatestVersion  pgtype.Text `json:"latest_version"`
}

func (q *Queries) SaveScannedModFile(ctx context.Context, arg SaveScannedModFileParams) (ModFile, error) {
	row := q.db.QueryRow(ctx, saveScannedModFile,
		arg.ModID,
		arg.Filename,
		arg.FilePath,
		arg.CurrentVersion,
		arg.LatestVersion,
	)
	var i ModFile
	err := row.Scan(
		&i.ID,
		&i.ModID,
		&i.Filename,
		&i.FilePath,
		&i.CurrentVersion,
		&i.LatestVersion,
		&i.GameVersionCompat,
		&i.IsEnabled,
		&i.Hash,
		&i.InstalledAt,
	)
	return i, err
}

const setModFileStatus = `-- name: SetModFileStatus :exec
UPDATE mod_files
SET is_enabled = $2
WHERE id = $1
`

type SetModFileStatusParams struct {
	ID        int32 `json:"id"`
	IsEnabled bool  `json:"is_enabled"`
}

func (q *Queries) SetModFileStatus(ctx context.Context, arg SetModFileStatusParams) error {
	_, err := q.db.Exec(ctx, setModFileStatus, arg.ID, arg.IsEnabled)
	return err
}

const updateModFileStatus = `-- name: UpdateModFileStatus :exec
UPDATE mod_files
SET file_path = $2
WHERE id = $1
`

type UpdateModFileStatusParams struct {
	ID       int32  `json:"id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) UpdateModFileStatus(ctx context.Context, arg UpdateModFileStatusParams) error {
	_, err := q.db.Exec(ctx, updateModFileStatus, arg.ID, arg.FilePath)
	return err
}

const updateModVersionCheck = `-- name: UpdateModVersionCheck :exec
UPDATE mod_files
SET latest_version = $2
WHERE mod_id = $1
`

type UpdateModVersionCheckParams struct {
	ModID         int32       `json:"mod_id"`
	LatestVersion pgtype.Text `json:"latest_version"`
}

func (q *Queries) UpdateModVersionCheck(ctx context.Context, arg UpdateModVersionCheckParams) error {
	_, err := q.db.Exec(ctx, updateModVersionCheck, arg.ModID, arg.LatestVersion)
	return err
}
