// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisableMod(arg1:number,arg2:string,arg3:string):Promise<void>;

export function EnableMod(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetRawDownloads():Promise<Array<string>>;

export function GetScannedMods():Promise<Array<main.ModFileResponse>>;

export function ImportModFile(arg1:string):Promise<string>;

export function ScanLocalMods(arg1:string):Promise<number>;
