// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DisableMod'](arg1, arg2, arg3);
}

export function EnableMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnableMod'](arg1, arg2, arg3);
}

export function GetRawDownloads() {
  return window['go']['main']['App']['GetRawDownloads']();
}

export function GetScannedMods() {
  return window['go']['main']['App']['GetScannedMods']();
}

export function ImportModFile(arg1) {
  return window['go']['main']['App']['ImportModFile'](arg1);
}

export function ScanLocalMods(arg1) {
  return window['go']['main']['App']['ScanLocalMods'](arg1);
}
